In [2]:
import pandas as pd

df = pd.read_csv("../data/raw/retail_store_inventory.csv")

df.shape

(73100, 15)

In [3]:
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                73100 non-null  object
 1   Store ID            73100 non-null  object
 2   Product ID          73100 non-null  object
 3   Category            73100 non-null  object
 4   Region              73100 non-null  object
 5   Inventory Level     73100 non-null  int64
 6   Units Sold          73100 non-null  int64
 7   Units Ordered       73100 non-null  int64
 8   Demand Forecast     73100 non-null  float64
 9   Price               73100 non-null  float64
 10  Discount            73100 non-null  int64
 11  Weather Condition   73100 non-null  object
 12  Holiday/Promotion   73100 non-null  int64
 13  Competitor Pricing  73100 non-null  float64
 14  Seasonality         73100 non-null  object
dtypes: float64(3), int64(5), object(7)
memory usage: 8.4+ MB

In [5]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Date,73100,731,2022-01-01,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Store ID,73100,5,S001,14620,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product ID,73100,20,P0001,3655,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,73100,5,Furniture,14699,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Region,73100,4,East,18349,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Inventory Level,73100.0,NaN,NaN,NaN,274.469877,129.949514,50.0,162.0,273.0,387.0,500.0
Units Sold,73100.0,NaN,NaN,NaN,136.46487,108.919406,0.0,49.0,107.0,203.0,499.0
Units Ordered,73100.0,NaN,NaN,NaN,110.004473,52.277448,20.0,65.0,110.0,155.0,200.0
Demand Forecast,73100.0,NaN,NaN,NaN,141.49472,109.254076,-9.99,53.67,113.015,208.0525,518.55
Price,73100.0,NaN,NaN,NaN,55.135108,26.021945,10.0,32.65,55.05,77.86,100.0
Discount,73100.0,NaN,NaN,NaN,10.009508,7.083746,0.0,5.0,10.0,15.0,20.0
Weather Condition,73100,4,Sunny,18290,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Holiday/Promotion,73100.0,NaN,NaN,NaN,0.497305,0.499996,0.0,0.0,0.0,1.0,1.0
Competitor Pricing,73100.0,NaN,NaN,NaN,55.146077,26.191408,5.03,32.68,55.01,77.82,104.94
Seasonality,73100,4,Spring,18317,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df["Store ID"].unique() # What Stores exist?

array(['S001', 'S002', 'S003', 'S004', 'S005'], dtype=object)

In [ ]:
df["Product ID"].unique() # What products exist?

array(['P0001', 'P0002', 'P0003', 'P0004', 'P0005', 'P0006', 'P0007',
       'P0008', 'P0009', 'P0010', 'P0011', 'P0012', 'P0013', 'P0014',
       'P0015', 'P0016', 'P0017', 'P0018', 'P0019', 'P0020'], dtype=object)

In [ ]:
df["Category"].unique() # What categories exist?

array(['Groceries', 'Toys', 'Electronics', 'Furniture', 'Clothing'],
      dtype=object)

In [ ]:
df["Region"].unique() # What are the regions?

array(['North', 'South', 'West', 'East'], dtype=object)

In [ ]:
df["Date"].min(), df["Date"].max() # What is the date range?

('2022-01-01', '2024-01-01')

In [ ]:
df.isna().sum() # Any missing values?

Date                  0
Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Units Ordered         0
Demand Forecast       0
Price                 0
Discount              0
Weather Condition     0
Holiday/Promotion     0
Competitor Pricing    0
Seasonality           0
dtype: int64

In [ ]:
df.duplicated().sum() # Any duplicate rows?

0

In [ ]:
# Verify the number of daily observations per Store × Product combination

# and how many combinations have each observation count.

# Output: 731 observations     100 Store × Product combinations

df.groupby(["Store ID", "Product ID"]).size().value_counts().sort_index()

731    100
Name: count, dtype: int64

In [ ]:
# Verify the first few dates represented in the dataset

df["Date"].value_counts().sort_index().head()

Date
2022-01-01    100
2022-01-02    100
2022-01-03    100
2022-01-04    100
2022-01-05    100
Name: count, dtype: int64

In [ ]:
# Verify the last few dates represented in the dataset

df["Date"].value_counts().sort_index().tail()

Date
2023-12-28    100
2023-12-29    100
2023-12-30    100
2023-12-31    100
2024-01-01    100
Name: count, dtype: int64

In [ ]:
# Verify that every date has the expected number of Store × Product observations

df.groupby("Date").size().value_counts().sort_index()

100    731
Name: count, dtype: int64

In [ ]:
# Check the number of unique values in every column

df.nunique()

Date                    731
Store ID                  5
Product ID               20
Category                  5
Region                    4
Inventory Level         451
Units Sold              498
Units Ordered           181
Demand Forecast       31608
Price                  8999
Discount                  5
Weather Condition         4
Holiday/Promotion         2
Competitor Pricing     9751
Seasonality               4
dtype: int64